# Generated by Django 6.1.1 on 2026-10-01 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Demo', max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=10000, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=22)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
