# Generated by Django 6.1.1 on 2026-10-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_signal_trade_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='duration_minutes',
            field=models.IntegerField(default=10, help_text='Kitne minute tak signal chalega (e.g., 10, 15)'),
        ),
        migrations.AddField(
            model_name='signal',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Kab se signal active hoga (e.g., 14:30)', null=True),
        ),
    ]
