# Generated by Django 6.1.1 on 2026-10-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_signal_duration_minutes_signal_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('UP', 'Show UP (fake rise)'), ('DOWN', 'Show DOWN (fake fall)')], max_length=4)),
                ('start_time', models.TimeField(help_text='Kab se override active hoga')),
                ('duration_minutes', models.IntegerField(default=15, help_text='Kitne minute tak')),
                ('intensity_percent', models.DecimalField(decimal_places=2, default=1.5, help_text='Kitna % offset lagayein (e.g., 1.5 = 1.5%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='signal',
            name='duration_minutes',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='signal',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
