# Generated by Django 6.1.1 on 2026-10-06 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_chartoverride_alter_signal_duration_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('LONG', 'Long (UP)'), ('SHORT', 'Short (DOWN)')], max_length=6)),
                ('entry_price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('close_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=14)),
                ('leverage', models.IntegerField(default=1)),
                ('position_size', models.DecimalField(decimal_places=2, max_digits=18)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=6)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='trading.account')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
